services:
  - type: web
    name: lumio-server
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run prisma:deploy && npm run build
    startCommand: NODE_ENV=production npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: COOKIE_DOMAIN
        sync: false
